### ISSUE TITLE
Dark mode in backstage make the azure storage explorer's prefix links a bit hard to read

### ISSUE THREAD

**Issue by QuadmanSWE** [deepan10/backstage-plugins#1]
Hi! awesome plugin, I really like it.

Running in darkmode makes the blue links appear a bit dull agains the background. Any quick patch to add some other color scheme?

![image](https://github.com/deepan10/backstage-plugins/assets/8070109/2bd75e62-0c06-4217-8e41-20b8681b1563)

![image](https://github.com/deepan10/backstage-plugins/assets/8070109/3a95e225-2536-4db4-b5af-31f08be18ae8)

Any plans to migrate it to the new backend? I had to import it through backend.add(legacyPlugin()) and it took me a while to get the name right.

![image](https://github.com/deepan10/backstage-plugins/assets/8070109/c23f4457-269f-4ff7-b43c-fadcf52f92b4)

**Comment by deepan10** [comment]
Hello @QuadmanSWE ,

Thanks for letting me know this. I am going to create a new release for the new backend system, and will keep updated.

**Comment by deepan10** [comment]
@QuadmanSWE 
1. UI Font color fixed
2. Now Azure Storage backend supports the new backend system.
